version: '3'
services:
  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      BACKEND_PORT: 9000
  frontend:
    build: ./frontend
    command: npm run start -- --host 0.0.0.0
    ports:
      - "8080:5000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      BACKEND_PORT: 9000
      FRONTEND_PORT: 5000
